/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.PantallaPrincipal;
import javax.swing.JOptionPane;
import sun.security.util.Password;

/**
 *
 * @author LENOVO
 */
public class AccesoAproAir extends javax.swing.JFrame {

    private Object txtUsuario;

    /**
     * Creates new form AccesoAproAir
     */
    public AccesoAproAir() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel LbUsuario = new javax.swing.JLabel();
        javax.swing.JButton jBuSalir = new javax.swing.JButton();
        javax.swing.JLabel LabImag = new javax.swing.JLabel();
        javax.swing.JLabel labelpassword = new javax.swing.JLabel();
        javax.swing.JPasswordField password = new javax.swing.JPasswordField();
        javax.swing.JTextField jTexUsuario = new javax.swing.JTextField();
        javax.swing.JButton jButton1Iniciar = new javax.swing.JButton();
        javax.swing.JLabel Labfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LbUsuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LbUsuario.setForeground(new java.awt.Color(255, 255, 255));
        LbUsuario.setText("USUARIO :");
        getContentPane().add(LbUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        jBuSalir.setBackground(new java.awt.Color(0, 51, 153));
        jBuSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBuSalir.setText("SALIR");
        jBuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jBuSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, -1, -1));

        LabImag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/images (3).jpg"))); // NOI18N
        getContentPane().add(LabImag, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, -1));

        labelpassword.setBackground(new java.awt.Color(51, 153, 255));
        labelpassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelpassword.setForeground(new java.awt.Color(255, 255, 255));
        labelpassword.setText("PASSWORD :");
        getContentPane().add(labelpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        password.setText("551218");
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 160, -1));

        jTexUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTexUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTexUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 160, -1));

        jButton1Iniciar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1Iniciar.setText("INICIAR SESION ");
        jButton1Iniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1IniciarMouseClicked(evt);
            }
        });
        getContentPane().add(jButton1Iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, -1));

        Labfondo.setBackground(new java.awt.Color(102, 102, 255));
        Labfondo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Labfondo.setForeground(new java.awt.Color(255, 255, 255));
        Labfondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Labfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(Labfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 664, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void jTexUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexUsuarioActionPerformed

    private void jButton1IniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1IniciarMouseClicked
         // TODO add your handling code here:
          String Usuario = "administrador";
          String Contraseña = "4528";
          
         String pass = new String(password.getpassword());
         if (txtUsuario.gettext().equals(Usuario) && pass.equals(Contraseña));
         
             PantallaPrincipal Pan = new PantallaPrincipal();
              Pan.setVisible(true);
              dispose();
     }
    else{
    
          JOptionPane.showInternalMessageDialog(this, "Usuario / contraseña incorrecta");
  

 
    }//GEN-LAST:event_jButton1IniciarMouseClicked

    private void jBuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jBuSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccesoAproAir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccesoAproAir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccesoAproAir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccesoAproAir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccesoAproAir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
