/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Descripcion;
import Modelo.PantallaPrincipal;

/**
 *
 * @author LENOVO
 */
public class Personaviws extends javax.swing.JFrame {

    /**
     * Creates new form Personaviws
     */
    public Personaviws() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JTextField jTextField5 = new javax.swing.JTextField();
        javax.swing.JLabel jLabel1nom = new javax.swing.JLabel();
        javax.swing.JLabel jLabel1Nombreproducto = new javax.swing.JLabel();
        javax.swing.JLabel jLabel1PRO = new javax.swing.JLabel();
        javax.swing.JLabel jLabel1cereza = new javax.swing.JLabel();
        javax.swing.JLabel jLabel1CEREVAI = new javax.swing.JLabel();
        javax.swing.JLabel jLabel1CHANNEL = new javax.swing.JLabel();
        javax.swing.JLabel jLabelDurazno = new javax.swing.JLabel();
        javax.swing.JLabel jLabelFrutosrojos = new javax.swing.JLabel();
        javax.swing.JLabel jLabel1Frutotropicales = new javax.swing.JLabel();
        javax.swing.JLabel jLabel1Lavanda = new javax.swing.JLabel();
        javax.swing.JLabel jLabel1Kiwi = new javax.swing.JLabel();
        javax.swing.JLabel jLabel1limon = new javax.swing.JLabel();
        javax.swing.JLabel jLabel1MANcane = new javax.swing.JLabel();
        javax.swing.JLabel jLabel1descrip = new javax.swing.JLabel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel7 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel9 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel10 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel11 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel12 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel13 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel14 = new javax.swing.JLabel();
        javax.swing.JButton jButton1Irpantaprinci = new javax.swing.JButton();
        javax.swing.JLabel jLabel15imagendescrip2 = new javax.swing.JLabel();
        javax.swing.JButton jButton1DESCRIPCION = new javax.swing.JButton();

        jTextField5.setText("jTextField5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1nom.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel1nom.setText("AROMA TERAPIA");

        jLabel1Nombreproducto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1Nombreproducto.setText("AIRE LIMPIO");

        jLabel1PRO.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1PRO.setText("BAMBU");

        jLabel1cereza.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1cereza.setText("CEREZA");

        jLabel1CEREVAI.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1CEREVAI.setText("CEREZA-VAINILLA");

        jLabel1CHANNEL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1CHANNEL.setText("CHANNEL");

        jLabelDurazno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelDurazno.setText("DURAZNO");

        jLabelFrutosrojos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelFrutosrojos.setText("FRUTOS ROJOS");

        jLabel1Frutotropicales.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1Frutotropicales.setText("FRUTOS TROPICALES");

        jLabel1Lavanda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1Lavanda.setText("LAVANDA");

        jLabel1Kiwi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1Kiwi.setText("KIWI");

        jLabel1limon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1limon.setText("LIMON-VAINILLA");

        jLabel1MANcane.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1MANcane.setText("MANDARINA-CANELA");

        jLabel1descrip.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel1descrip.setText("DESCRIPCION");

        jLabel1.setText("La necesidad de respirar un aire limpio");

        jLabel2.setText("Exotico y suave es una fragancia de notas frescas, herbaceas y suaves");

        jLabel3.setText("Aroma de la juventud, la alegria,  la dicha aumenta el magnetismo");

        jLabel4.setText("El aroma suave aumenta el amor con el espiritu calido y tranquilo");

        jLabel5.setText("Abre energias cosmicas, equilibra y refuerza las habilidades intuitivas");

        jLabel6.setText("Estimula, activa la percepcion extra sensorial, relajante");

        jLabel7.setText("Genera un descanso relajante que trasforma tu vida en felicidad y descanso");

        jLabel9.setText("Estimula la creatividad, otorga buen humor, estimulo actitudes positivas");

        jLabel10.setText("Atrae prosperidad, calma los dolores de cabeza, y el insomnio, afrodisiaco");

        jLabel11.setText("Una aroma de tranquilidad al hogar, buenos negocios, salud, pureza ");

        jLabel12.setText("controla vibraciones negativas, actua como depurador ambiental");

        jLabel13.setText("Atrae la prosperidad, disminuir fatiga y estres, espiritual,calido y tranquilo");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/asdasdasd.png"))); // NOI18N

        jButton1Irpantaprinci.setBackground(new java.awt.Color(0, 102, 255));
        jButton1Irpantaprinci.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1Irpantaprinci.setText("IR A PANTALLA PRINCIPAL");
        jButton1Irpantaprinci.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1IrpantaprinciMouseClicked(evt);
            }
        });

        jLabel15imagendescrip2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aromas.jpg"))); // NOI18N

        jButton1DESCRIPCION.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1DESCRIPCION.setText("DESCRIPCION DEL PRODUCTO");
        jButton1DESCRIPCION.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1DESCRIPCIONMouseClicked(evt);
            }
        });
        jButton1DESCRIPCION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1DESCRIPCIONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1Kiwi)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1CEREVAI)
                            .addComponent(jLabel1CHANNEL)
                            .addComponent(jLabelDurazno)
                            .addComponent(jLabel1Lavanda)
                            .addComponent(jLabel1limon))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel13))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1Nombreproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1nom, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1PRO)
                        .addComponent(jLabel1cereza))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jLabel1descrip, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1Frutotropicales)
                            .addComponent(jLabelFrutosrojos)
                            .addComponent(jLabel1MANcane))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15imagendescrip2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1Irpantaprinci)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGap(311, 311, 311)
                .addComponent(jButton1DESCRIPCION)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton1DESCRIPCION)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1descrip, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1nom, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1Nombreproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1PRO)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1cereza)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1CEREVAI)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1CHANNEL)
                                    .addComponent(jLabel5))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelDurazno))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8))
                            .addComponent(jLabel1MANcane))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFrutosrojos, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel1Frutotropicales))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1Lavanda)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1Kiwi)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1limon)
                            .addComponent(jLabel12))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15imagendescrip2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1Irpantaprinci)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1DESCRIPCIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1DESCRIPCIONActionPerformed
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_jButton1DESCRIPCIONActionPerformed

    private void jButton1DESCRIPCIONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1DESCRIPCIONMouseClicked
     Descripcion a = new Descripcion();
     a.setvisible(true);
     this.setVisible(false);
    }//GEN-LAST:event_jButton1DESCRIPCIONMouseClicked

    private void jButton1IrpantaprinciMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1IrpantaprinciMouseClicked
        PantallaPrincipal p = new PantallaPrincipal();
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1IrpantaprinciMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Personaviws.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Personaviws.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Personaviws.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Personaviws.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Personaviws().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
